aroma:

alter table `Order Transaction Fact`  PARTITION BY RANGE (year(`Invoice Date`))
SUBPARTITION BY KEY (`Store Key`)
SUBPARTITIONS 2 (
PARTITION pold VALUES LESS THAN (2019) ENGINE = InnoDB,
PARTITION p2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
PARTITION p2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
PARTITION p2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
PARTITION p2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
PARTITION p2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
 PARTITION pcurrent VALUES LESS THAN MAXVALUE ENGINE = InnoDB);


alter table `Inventory Transaction Fact` PARTITION BY RANGE (year(`Date`))
    (
    PARTITION pold VALUES LESS THAN (2020) ENGINE = InnoDB,
    PARTITION p20 VALUES LESS THAN (2021) ENGINE = InnoDB,
    PARTITION p21 VALUES LESS THAN (2022) ENGINE = InnoDB,
    PARTITION p22 VALUES LESS THAN (2023) ENGINE = InnoDB,
    PARTITION p23 VALUES LESS THAN (2024) ENGINE = InnoDB,
    PARTITION pnow VALUES LESS THAN MAXVALUE ENGINE = InnoDB);

spain:

alter table `Order Transaction Fact`  PARTITION BY RANGE (year(`Invoice Date`))
    SUBPARTITION BY KEY (`Store Key`)
    SUBPARTITIONS 17 (
    PARTITION pold VALUES LESS THAN (2019) ENGINE = InnoDB,
    PARTITION p2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
    PARTITION p2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
    PARTITION p2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
    PARTITION p2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
    PARTITION p2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
    PARTITION pcurrent VALUES LESS THAN MAXVALUE ENGINE = InnoDB);