					<option value="AF">{t}Afganistán{/t}</option>
					<option value="AL">{t}Albania{/t}</option>
					<option value="DZ">{t}Algeria{/t}</option>
					<option value="AS">{t}Samoa Americana{/t}</option>
					<option value="AD">{t}Andorra{/t}</option>
					<option value="AO">{t}Angola{/t}</option>
					<option value="AI">{t}Anguilla{/t}</option>
					<option value="AQ">{t}Antártida{/t}</option>
					<option value="AG">{t}Antigua and Barbuda{/t}</option>
					<option value="AR">{t}Argentina{/t}</option>
					<option value="AM">{t}Armenia{/t}</option>
					<option value="AW">{t}Aruba{/t}</option>
					<option value="AU">{t}Australia{/t}</option>
					<option value="AT">{t}Austria{/t}</option>
					<option value="AZ">{t}Azerbaiyán{/t}</option>
					<option value="BS">{t}Bahamas{/t}</option>
					<option value="BH">{t}Bahrain{/t}</option>
					<option value="BD">{t}Bangladesh{/t}</option>
					<option value="BB">{t}Barbados{/t}</option>
					<option value="BY">{t}Belarús{/t}</option>
					<option value="BE">{t}Bélgica{/t}</option>
					<option value="BZ">{t}Belize{/t}</option>
					<option value="BJ">{t}Benin{/t}</option>
					<option value="BM">{t}Bermuda{/t}</option>
					<option value="BT">{t}Bután{/t}</option>
					<option value="BO">{t}Bolivia{/t}</option>
					<option value="BA">{t}Bosnia-Herzegovina{/t}</option>
					<option value="BW">{t}Botswana{/t}</option>
					<option value="BV">{t}Isla Bouvet{/t}</option>
					<option value="BR">{t}Brasil{/t}</option>
					<option value="IO">{t}British Indian Ocean Territory{/t}</option>
					<option value="BN">{t}Brunei Darussalam{/t}</option>
					<option value="BG">{t}Bulgaria{/t}</option>
					<option value="BF">{t}Burkina Faso{/t}</option>
					<option value="BI">{t}Burundi{/t}</option>
					<option value="KH">{t}Camboya{/t}</option>
					<option value="CM">{t}Camerún{/t}</option>
					<option value="CA">{t}Canadá{/t}</option>
					<option value="CV">{t}Cabo Verde{/t}</option>
					<option value="KY">{t}Islas Caimán{/t}</option>
					<option value="CF">{t}República Centroafricana{/t}</option>
					<option value="TD">{t}Chad{/t}</option>
					<option value="CL">{t}Chile{/t}</option>
					<option value="CN">{t}China{/t}</option>
					<option value="CX">{t}Isla de Navidad{/t}</option>
					<option value="CC">{t}Islas Cocos (Keeling){/t}</option>
					<option value="CO">{t}Colombia{/t}</option>
					<option value="KM">{t}Comoros{/t}</option>
					<option value="CG">{t}Congo{/t}</option>
					<option value="CK">{t}Islas Cook{/t}</option>
					<option value="CR">{t}Costa Rica{/t}</option>
					<option value="HR">{t}Croacia{/t}</option>
					<option value="CU">{t}Cuba{/t}</option>
					<option value="CY">{t}Chipre{/t}</option>
					<option value="CZ">{t}República Checa{/t}</option>
					<option value="DK">{t}Dinamarca{/t}</option>
					<option value="DJ">{t}Djibouti{/t}</option>
					<option value="DM">{t}Dominica{/t}</option>
					<option value="DO">{t}República Dominicana{/t}</option>
					<option value="TP">{t}Timor Oriental{/t}</option>
					<option value="EC">{t}Ecuador{/t}</option>
					<option value="EG">{t}Egipto{/t}</option>
					<option value="SV">{t}El Salvador{/t}</option>
					<option value="GQ">{t}Guinea Ecuatorial{/t}</option>
					<option value="ER">{t}Eritrea{/t}</option>
					<option value="EE">{t}Estonia{/t}</option>
					<option value="ET">{t}Etiopía{/t}</option>
					<option value="FK">{t}Islas Malvinas{/t}</option>
					<option value="FO">{t}Islas Faroe{/t}</option>
					<option value="FJ">{t}Fiji{/t}</option>
					<option value="FI">{t}Finlandia{/t}</option>
					<option value="FR">{t}Francia{/t}</option>
					<option value="GF">{t}French Guyana{/t}</option>
					<option value="TF">{t}Territorios Australes Franceses{/t}</option>
					<option value="GA">{t}Gabón{/t}</option>
					<option value="GM">{t}Gambia{/t}</option>
					<option value="GE">{t}Georgia{/t}</option>
					<option value="DE">{t}Alemania{/t}</option>
					<option value="GH">{t}Ghana{/t}</option>
					<option value="GI">{t}Gibraltar{/t}</option>
					<option value="GB">{t}Gran Bretaña{/t}</option>
					<option value="GR">{t}Grecia{/t}</option>
					<option value="GL">{t}Groenlandia{/t}</option>
					<option value="GD">{t}Grenada{/t}</option>
					<option value="GP">{t}Guadalupe (Francia){/t}</option>
					<option value="GU">{t}Guam (EE.UU.){/t}</option>
					<option value="GT">{t}Guatemala{/t}</option>
					<option value="GN">{t}Guinea{/t}</option>
					<option value="GW">{t}Guinea Bissau{/t}</option>
					<option value="GY">{t}Guyana{/t}</option>
					<option value="HT">{t}Haití{/t}</option>
					<option value="HM">{t}Heard and McDonald Islands{/t}</option>
					<option value="HN">{t}Honduras{/t}</option>
					<option value="HK">{t}Hong Kong{/t}</option>
					<option value="HU">{t}Hungría{/t}</option>
					<option value="IS">{t}Islandia{/t}</option>
					<option value="IN">{t}India{/t}</option>
					<option value="ID">{t}Indonesia{/t}</option>
					<option value="IR">{t}Irán{/t}</option>
					<option value="IQ">{t}Iraq{/t}</option>
					<option value="IE">{t}Irlanda{/t}</option>
					<option value="IL">{t}Israel{/t}</option>
					<option value="IT">{t}Italia{/t}</option>
					<option value="CI">{t}Costa del Marfil{/t}</option>
					<option value="JM">{t}Jamaica{/t}</option>
					<option value="JP">{t}Japón{/t}</option>
					<option value="JO">{t}Jordan{/t}</option>
					<option value="KZ">{t}Kazajstán{/t}</option>
					<option value="KE">{t}Kenya{/t}</option>
					<option value="KI">{t}Kiribati{/t}</option>
					<option value="KW">{t}Kuwait{/t}</option>
					<option value="KG">{t}Kirguistán{/t}</option>
					<option value="LA">{t}Laos{/t}</option>
					<option value="LV">{t}Latvia{/t}</option>
					<option value="LB">{t}Líbano{/t}</option>
					<option value="LS">{t}Lesotho{/t}</option>
					<option value="LR">{t}Liberia{/t}</option>
					<option value="LY">{t}Libya{/t}</option>
					<option value="LI">{t}Liechtenstein{/t}</option>
					<option value="LT">{t}Lituania{/t}</option>
					<option value="LU">{t}Luxemburgo{/t}</option>
					<option value="MO">{t}Macau{/t}</option>
					<option value="MK">{t}Macedonia{/t}</option>
					<option value="MG">{t}Madagascar{/t}</option>
					<option value="MW">{t}Malawi{/t}</option>
					<option value="MY">{t}Malasia{/t}</option>
					<option value="MV">{t}Maldives{/t}</option>
					<option value="ML">{t}Malí{/t}</option>
					<option value="MT">{t}Malta{/t}</option>
					<option value="MH">{t}Islas Marshall{/t}</option>
					<option value="MQ">{t}Martinica (Francia){/t}</option>
					<option value="MR">{t}Mauritania{/t}</option>
					<option value="MU">{t}Mauritius{/t}</option>
					<option value="YT">{t}Mayotte{/t}</option>
					<option value="MX">{t}Mexico{/t}</option>
					<option value="FM">{t}Micronesia{/t}</option>
					<option value="MD">{t}Moldavia{/t}</option>
					<option value="MC">{t}Monaco{/t}</option>
					<option value="MN">{t}Mongolia{/t}</option>
					<option value="MS">{t}Montserrat{/t}</option>
					<option value="MA">{t}Morocco{/t}</option>
					<option value="MZ">{t}Mozambique{/t}</option>
					<option value="MM">{t}Myanmar{/t}</option>
					<option value="NA">{t}Namibia{/t}</option>
					<option value="NR">{t}Nauru{/t}</option>
					<option value="NP">{t}Nepal{/t}</option>
					<option value="NL">{t}Netherlands{/t}</option>
					<option value="AN">{t}Netherlands Antilles{/t}</option>
					<option value="NT">{t}Neutral Zone{/t}</option>
					<option value="NC">{t}New Caledonia (French){/t}</option>
					<option value="NZ">{t}New Zealand{/t}</option>
					<option value="NI">{t}Nicaragua{/t}</option>
					<option value="NE">{t}Niger{/t}</option>
					<option value="NG">{t}Nigeria{/t}</option>
					<option value="NU">{t}Niue{/t}</option>
					<option value="NF">{t}Norfolk Island{/t}</option>
					<option value="KP">{t}North Korea{/t}</option>
					<option value="MP">{t}Northern Mariana Islands{/t}</option>
					<option value="NO">{t}Norway{/t}</option>
					<option value="OM">{t}Oman{/t}</option>
					<option value="PK">{t}Pakistan{/t}</option>
					<option value="PW">{t}Palau{/t}</option>
					<option value="PA">{t}Panama{/t}</option>
					<option value="PG">{t}Papua New Guinea{/t}</option>
					<option value="PY">{t}Paraguay{/t}</option>
					<option value="PE">{t}Peru{/t}</option>
					<option value="PH">{t}Philippines{/t}</option>
					<option value="PN">{t}Pitcairn Island{/t}</option>
					<option value="PL">{t}Poland{/t}</option>
					<option value="PF">{t}Polynesia (French){/t}</option>
					<option value="PT">{t}Portugal{/t}</option>
					<option value="PR">{t}Puerto Rico{/t}</option>
					<option value="QA">{t}Qatar{/t}</option>
					<option value="RE">{t}Reunion (French){/t}</option>
					<option value="RO">{t}Romania{/t}</option>
					<option value="RU">{t}Russian Federation{/t}</option>
					<option value="RW">{t}Rwanda{/t}</option>
					<option value="GS">{t}S. Georgia & S. Sandwich I.{/t}</option>
					<option value="SH">{t}Saint Helena{/t}</option>
					<option value="KN">{t}Saint Kitts & Nevis Anguilla{/t}</option>
					<option value="LC">{t}Saint Lucia{/t}</option>
					<option value="PM">{t}St Pierre and Miquelon{/t}</option>
					<option value="ST">{t}St Tome & Principe{/t}</option>
					<option value="VC">{t}St Vincent & Grenadines{/t}</option>
					<option value="WS">{t}Samoa{/t}</option>
					<option value="SM">{t}San Marino{/t}</option>
					<option value="SA">{t}Saudi Arabia{/t}</option>
					<option value="SN">{t}Senegal{/t}</option>
					<option value="SC">{t}Seychelles{/t}</option>
					<option value="SL">{t}Sierra Leone{/t}</option>
					<option value="SG">{t}Singapore{/t}</option>
					<option value="SK">{t}Slovak Republic{/t}</option>
					<option value="SI">{t}Slovenia{/t}</option>
					<option value="SB">{t}Solomon Islands{/t}</option>
					<option value="SO">{t}Somalia{/t}</option>
					<option value="ZA">{t}South Africa{/t}</option>
					<option value="KR">{t}South Korea{/t}</option>
					<option value="ES">{t}Spain{/t}</option>
					<option value="LK">{t}Sri Lanka{/t}</option>
					<option value="SD">{t}Sudan{/t}</option>
					<option value="SR">{t}Suriname{/t}</option>
					<option value="SJ">{t}Svalbard and Jan Mayen I.{/t}</option>
					<option value="SZ">{t}Swaziland{/t}</option>
					<option value="SE">{t}Sweden{/t}</option>
					<option value="CH">{t}Switzerland{/t}</option>
					<option value="SY">{t}Syria{/t}</option>
					<option value="TJ">{t}Tadjikistan{/t}</option>
					<option value="TW">{t}Taiwan{/t}</option>
					<option value="TZ">{t}Tanzania{/t}</option>
					<option value="TH">{t}Thailand{/t}</option>
					<option value="TG">{t}Togo{/t}</option>
					<option value="TK">{t}Tokelau{/t}</option>
					<option value="TO">{t}Tonga{/t}</option>
					<option value="TT">{t}Trinidad and Tobago{/t}</option>
					<option value="TN">{t}Tunisia{/t}</option>
					<option value="TR">{t}Turkey{/t}</option>
					<option value="TM">{t}Turkmenistan{/t}</option>
					<option value="TC">{t}Turks and Caicos Islands{/t}</option>
					<option value="TV">{t}Tuvalu{/t}</option>
					<option value="UG">{t}Uganda{/t}</option>
					<option value="UA">{t}Ukraine{/t}</option>
					<option value="AE">{t}United Arab Emirates{/t}</option>
					<option value="GB">{t}United Kingdom{/t}</option>
					<option value="US">{t}United States{/t}</option>
					<option value="UY">{t}Uruguay{/t}</option>
					<option value="UM">{t}USA Minor Outlying Islands{/t}</option>
					<option value="UZ">{t}Uzbekistan{/t}</option>
					<option value="VU">{t}Vanuatu{/t}</option>
					<option value="VA">{t}Vatican City State{/t}</option>
					<option value="VE">{t}Venezuela{/t}</option>
					<option value="VN">{t}Vietnam{/t}</option>
					<option value="VG">{t}Virgin Islands (British){/t}</option>
					<option value="VI">{t}Virgin Islands (USA){/t}</option>
					<option value="WF">{t}Wallis and Futuna Islands{/t}</option>
					<option value="EH">{t}Western Sahara{/t}</option>
					<option value="YE">{t}Yemen{/t}</option>
					<option value="YU">{t}Yugoslavia{/t}</option>
					<option value="ZR">{t}Zaire{/t}</option>
					<option value="ZM">{t}Zambia{/t}</option>
					<option value="ZW">{t}Zimbabwe{/t}</option>