# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: alpine

pipelines:
  branches:
    master:
      - step:
          name: 'Deployment to Production'
          deployment: production
          script:
            - echo "Deployed by Buddy..."
