CREATE TABLE `Store Emails Data` (
                              `Store Emails Store Key` mediumint unsigned NOT NULL,
                              `Store Total Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Total Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Total Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store 1 Year Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store 1 Quarter Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store 1 Month Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store 1 Week Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Year To Day Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Quarter To Day Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Month To Day Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Week To Day Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Last Month Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Last Week Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Yesterday Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Today Acc Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc Mailshots` int unsigned NOT NULL DEFAULT '0',


                              `Store 1 Year Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store 1 Year Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Year Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store 1 Quarter Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Quarter Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store 1 Month Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Month Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store 1 Week Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store 1 Week Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Year To Day Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Year To Day Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Quarter To Day Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Quarter To Day Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Month To Day Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Month To Day Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Week To Day Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Week To Day Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Last Month Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Month Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Last Week Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Last Week Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Yesterday Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Yesterday Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB Newsletter Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB Marketing Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB AbandonedCart Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB Newsletter Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB Marketing Mailshots` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB AbandonedCart Mailshots` int unsigned NOT NULL DEFAULT '0',

                              `Store Today Acc 1YB Emails` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB Emails Open` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB Emails Unsubscribed` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB Emails Clicked` int unsigned NOT NULL DEFAULT '0',
                              `Store Today Acc 1YB Mailshots` int unsigned NOT NULL DEFAULT '0',
                              
                              
                   
                              PRIMARY KEY (`Store Emails Store Key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;