ALTER TABLE `Page Store Dimension`
    DROP `Page Parent Key`,
    DROP `Page Parent Code`,
    DROP `Page Store Section Type`,
    DROP `Page Store Section Key`,
    DROP `Page Store Section`,
    DROP `Page Locale`,
    DROP `Page Store Title`,
    DROP `Page Head Include`,
    DROP `Page Use Site Body Include`,
    DROP `Page Store CSS`,
    DROP `Page Store Published CSS`,
    DROP `Page Store Creation Date`,
    DROP `Page Store Last Update Date`,
    DROP `Page Store Last Structural Change Date`,
    DROP `Number See Also Links`,
    DROP `Number Found In Links`,
    DROP `Number Lists`,
    DROP `Number Products In Lists`,
    DROP `Number Buttons`,
    DROP `Page Store Image URL`,
    DROP `Page Store Image Key`,
    DROP `Page Related Products List`,
    DROP `Page See Also Last Updated`;