insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-04-01',"EURGBP", 0.9285 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-05-01',"EURGBP", 0.89035  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-06-01',"EURGBP", 0.87060  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-07-01',"EURGBP", 0.85430  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-08-01',"EURGBP", 0.8611  ); 
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-09-01',"EURGBP", 0.8804 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-10-01',"EURGBP", 0.92265 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-11-01',"EURGBP", 0.9057 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-12-01',"EURGBP", 0.911 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-01-01',"EURGBP", 0.8918 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-02-01',"EURGBP", 0.86725 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-03-01',"EURGBP", 0.8775 );

insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2009-12-01',"GBPGBP",1  );

insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2010-12-01',"GBPGBP",1  );

insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2011-12-01',"GBPGBP",1  );

insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2003-12-01',"GBPGBP",1  );

insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2004-12-01',"GBPGBP",1  );


insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2005-12-01',"GBPGBP",1  );

insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2006-12-01',"GBPGBP",1  );

insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2007-12-01',"GBPGBP",1  );

insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-01-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-02-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-03-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-04-01',"GBPGBP", 1 );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-05-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-06-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-07-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-08-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-09-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-10-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-11-01',"GBPGBP", 1  );
insert into kbase.`HM Revenue and Customs Currency Exchange Dimension` values('2008-12-01',"GBPGBP",1  );