					<option value="AF">Afganistán</option>
					<option value="AL">Albania</option>
										<option value="DE">Alemania</option>

					<option value="DZ">Algeria</option>
					<option value="AD">Andorra</option>
					<option value="AO">Angola</option>
					<option value="AI">Anguilla</option>
					<option value="AQ">Antártida</option>
					<option value="AG">Antigua and Barbuda</option>
					<option value="AR">Argentina</option>
					<option value="AM">Armenia</option>
					<option value="AW">Aruba</option>
					<option value="AU">Australia</option>
					<option value="AT">Austria</option>
					<option value="AZ">Azerbaiyán</option>
					<option value="BS">Bahamas</option>
					<option value="BH">Bahrain</option>
					<option value="BD">Bangladesh</option>
					<option value="BB">Barbados</option>
					<option value="BY">Belarús</option>
					<option value="BE">Bélgica</option>
					<option value="BZ">Belice</option>
					<option value="BJ">Benin</option>
					<option value="BM">Bermuda</option>
					<option value="BT">Bután</option>
					<option value="BO">Bolivia</option>
					<option value="BA">Bosnia-Herzegovina</option>
					<option value="BW">Botswana</option>
					<option value="BV">Bouvet (Isla)</option>
					<option value="BR">Brasil</option>
					<option value="IO">British Indian Ocean Territory</option>
					<option value="BN">Brunei Darussalam</option>
					<option value="BG">Bulgaria</option>
					<option value="BF">Burkina Faso</option>
					<option value="BI">Burundi</option>
					<option value="KH">Camboya</option>
					<option value="CM">Camerún</option>
					<option value="CA">Canadá</option>
					<option value="CV">Cabo Verde</option>
					<option value="KY">Islas Caimán</option>
					<option value="CF">República Centroafricana</option>
					<option value="TD">Chad</option>
					<option value="CL">Chile</option>
					<option value="CN">China</option>
					<option value="CX">Navidad (Isla de)</option>
					<option value="CC">Cocos, Keeling (Islas)</option>
					<option value="CO">Colombia</option>
					<option value="KM">Comoros</option>
					<option value="CG">Congo</option>
					<option value="CK">Cook (Islas)</option>
					<option value="CR">Costa Rica</option>
					<option value="HR">Croacia</option>
					<option value="CU">Cuba</option>
					<option value="CY">Chipre</option>
					<option value="CZ">República Checa</option>
					<option value="DK">Dinamarca</option>
					<option value="DJ">Djibouti</option>
					<option value="DM">Dominica</option>
					<option value="DO">República Dominicana</option>
					<option value="TP">Timor Oriental</option>
					<option value="EC">Ecuador</option>
					<option value="EG">Egipto</option>
					<option value="SV">El Salvador</option>
					<option value="ER">Eritrea</option>
										<option value="ES">España</option>

					<option value="EE">Estonia</option>
					<option value="ET">Etiopía</option>
					<option value="FK">Islas Malvinas</option>
					<option value="FO">Islas Faroe</option>
					<option value="FJ">Fiji</option>
					<option value="FI">Finlandia</option>
					<option value="FR">Francia</option>
					<option value="GF">French Guyana</option>
					<option value="TF">Territorios Australes Franceses</option>
					<option value="GA">Gabón</option>
					<option value="GM">Gambia</option>
					<option value="GE">Georgia</option>
					<option value="GH">Ghana</option>
					<option value="GI">Gibraltar</option>
										<option value="GQ">Guinea Ecuatorial</option>

					<option value="GB">Gran Bretaña</option>
					<option value="GR">Grecia</option>
					<option value="GL">Groenlandia</option>
					<option value="GD">Grenada</option>
					<option value="GP">Guadalupe (Francia)</option>
					<option value="GU">Guam (EE.UU.)</option>
					<option value="GT">Guatemala</option>
					<option value="GN">Guinea</option>
					<option value="GW">Guinea Bissau</option>
					<option value="GY">Guyana</option>
					<option value="HT">Haití</option>
					<option value="HM">Heard and McDonald (Islas)</option>
					<option value="HN">Honduras</option>
					<option value="HK">Hong Kong</option>
					<option value="HU">Hungría</option>
					<option value="IS">Islandia</option>
					<option value="IN">India</option>
					<option value="ID">Indonesia</option>
					<option value="IR">Irán</option>
					<option value="IQ">Iraq</option>
					<option value="IE">Irlanda</option>
					<option value="IL">Israel</option>
					<option value="IT">Italia</option>
					<option value="CI">Costa del Marfil</option>
					<option value="JM">Jamaica</option>
					<option value="JP">Japón</option>
					<option value="JO">Jordan</option>
					<option value="KZ">Kazajstán</option>
					<option value="KE">Kenya</option>
					<option value="KI">Kiribati</option>
					<option value="KW">Kuwait</option>
					<option value="KG">Kirguistán</option>
					<option value="LA">Laos</option>
					<option value="LV">Latvia</option>
					<option value="LB">Líbano</option>
					<option value="LS">Lesotho</option>
					<option value="LR">Liberia</option>
					<option value="LY">Libya</option>
					<option value="LI">Liechtenstein</option>
					<option value="LT">Lituania</option>
					<option value="LU">Luxemburgo</option>
					<option value="MO">Macau</option>
					<option value="MK">Macedonia</option>
					<option value="MG">Madagascar</option>
					<option value="MW">Malawi</option>
					<option value="MY">Malasia</option>
					<option value="MV">Maldives</option>
					<option value="ML">Malí</option>
					<option value="MT">Malta</option>
					<option value="MH">Islas Marshall</option>
					<option value="MR">Mauritania</option>
					<option value="MU">Mauritius</option>
					<option value="YT">Mayotte</option>
					<option value="MX">México</option>
					<option value="FM">Micronesia</option>
					<option value="MD">Moldavia</option>
					<option value="MC">Monaco</option>
					<option value="MN">Mongolia</option>
					<option value="MS">Montserrat</option>
					<option value="MA">Maruecos</option>
					<option value="MZ">Mozambique</option>
					<option value="MM">Myanmar</option>
					<option value="NA">Namibia</option>
					<option value="NR">Nauru</option>
					<option value="NP">Nepal</option>
					<option value="NL">Netherlands</option>
					<option value="AN">Netherlands Antilles</option>
					<option value="NT">Neutral Zone</option>
					<option value="NC">New Caledonia (French)</option>
					<option value="NZ">New Zealand</option>
					<option value="NI">Nicaragua</option>
					<option value="NE">Niger</option>
					<option value="NG">Nigeria</option>
					<option value="NU">Niue</option>
					<option value="NF">Norfolk Island</option>
					<option value="KP">Corea del Norte</option>
					<option value="MP">Northern Mariana Islands</option>
					<option value="NO">Noruega</option>
					<option value="OM">Oman</option>
					<option value="PK">Pakistan</option>
					<option value="PW">Palau</option>
					<option value="PA">Panama</option>
					<option value="PG">Papua New Guinea</option>
					<option value="PY">Paraguay</option>
					<option value="PE">Peru</option>
					<option value="PH">Philippines</option>
					<option value="PN">Pitcairn Island</option>
					<option value="PL">Polonia</option>
					<option value="PF">Polynesia (French)</option>
					<option value="PT">Portugal</option>
					<option value="PR">Puerto Rico</option>
					<option value="QA">Qatar</option>
					<option value="RE">Reunion (Francia)</option>
					<option value="RO">Romania</option>
					<option value="RU">Rusia (Federacion)</option>
					<option value="RW">Rwanda</option>
					<option value="GS">S. Georgia & S. Sandwich I.</option>
					<option value="SH">Saint Helena</option>
					<option value="KN">Saint Kitts & Nevis Anguilla</option>
					<option value="LC">Saint Lucia</option>
					<option value="PM">St Pierre and Miquelon</option>
					<option value="ST">St Tome & Principe</option>
					<option value="VC">St Vincent & Grenadines</option>
					<option value="WS">Samoa</option>
										<option value="AS">Samoa Americana</option>

					<option value="SM">San Marino</option>
					<option value="SA">Saudi Arabia</option>
					<option value="SN">Senegal</option>
					<option value="SC">Seychelles</option>
					<option value="SL">Sierra Leona</option>
					<option value="SG">Singapore</option>
					<option value="SK">Slovak Republic</option>
					<option value="SI">Slovenia</option>
					<option value="SB">Solomon Islands</option>
					<option value="SO">Somalia</option>
					<option value="ZA">South Africa</option>
					<option value="KR">Corea del Sur</option>
					<option value="LK">Sri Lanka</option>
					<option value="SD">Sudan</option>
					<option value="SR">Suriname</option>
					<option value="SJ">Svalbard and Jan Mayen I.</option>
					<option value="SZ">Swaziland</option>
					<option value="SE">Suecia</option>
					<option value="CH">Switzerland</option>
					<option value="SY">Siria</option>
					<option value="TJ">Tadjikistan</option>
					<option value="TW">Taiwan</option>
					<option value="TZ">Tanzania</option>
					<option value="TH">Tailandia</option>
					<option value="TG">Togo</option>
					<option value="TK">Tokelau</option>
					<option value="TO">Tonga</option>
					<option value="TT">Trinidad and Tobago</option>
					<option value="TN">Tunisia</option>
					<option value="TR">Turquia</option>
					<option value="TM">Turkmenistan</option>
					<option value="TC">Turks and Caicos Islands</option>
					<option value="TV">Tuvalu</option>
					<option value="UG">Uganda</option>
					<option value="UA">Ukraine</option>
					<option value="AE">Emiratos Arabes Unidos</option>
					<option value="GB">Reino Unido</option>
					<option value="US">Estados Unidos</option>
					<option value="UY">Uruguay</option>
					<option value="UM">USA Minor Outlying Islands</option>
					<option value="UZ">Uzbekistan</option>
					<option value="VU">Vanuatu</option>
					<option value="VA">Vaticano</option>
					<option value="VE">Venezuela</option>
					<option value="VN">Vietnam</option>
					<option value="VG">Virgin Islands (British)</option>
					<option value="VI">Virgin Islands (USA)</option>
					<option value="WF">Wallis and Futuna Islands</option>
					<option value="EH">Western Sahara</option>
					<option value="YE">Yemen</option>
					<option value="ZR">Zaire</option>
					<option value="ZM">Zambia</option>
					<option value="ZW">Zimbabwe</option>